package main

import (
	"fmt"
	"log/slog"
	"os"

	_ "base-code-go-gin-clean/docs" // docs is generated by Swag CLI, you have to import it.
	"base-code-go-gin-clean/internal/config"
	"base-code-go-gin-clean/internal/service"
	"base-code-go-gin-clean/pkg/logger"
	"base-code-go-gin-clean/wire"

	"github.com/joho/godotenv"
)

// @title           Base Code Go Gin Clean API
// @version         1.0
// @description     This is a sample server for a clean Go Gin application.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /api/v1

// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

func main() {
	// Load .env file into environment variables
	_ = godotenv.Load()
	// Use Wire injector for HTTP server
	srv, err := wire.InitializeServer()
	if err != nil {
		slog.Error("Failed to initialize server", "error", err)
		os.Exit(1)
	}

	// Load config for other services
	cfg, err := config.Load()

	fmt.Println(cfg)

	if err != nil {
		slog.Error("Failed to load config", "error", err)
		os.Exit(1)
	}

	log := logger.New(cfg.Server.Environment)

	// Initialize cron service
	cronSvc := service.NewCronService()

	// Initialize daily report service
	dailyReportSvc := service.NewDailyReportService(service.NewEmailService(cfg))

	// Register all cron jobs from the registry
	for _, job := range service.GetCronJobs(dailyReportSvc) {
		_, err := cronSvc.AddJob(job.Spec, job.Handler)
		if err != nil {
			log.Error("Failed to schedule cron job", "spec", job.Spec, "error", err)
			os.Exit(1)
		}
	}

	// Start cron service
	cronSvc.Start()
	defer cronSvc.Stop()

	log.Info("Cron jobs started")

	// Start server and handle graceful shutdown
	if err := srv.Start(); err != nil {
		log.Error("Server error", "error", err)
		os.Exit(1)
	}
}
