package mocks

import (
	"context"

	"base-code-go-gin-clean/internal/domain/user"
	"github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// GetUserByID provides a mock function with given fields: ctx, id
func (m *UserService) GetUserByID(ctx context.Context, id string) (*user.UserResponse, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*user.UserResponse), args.Error(1)
}

// On provides a mock function with given fields: methodName, arguments...
func (m *UserService) On(methodName string, arguments ...interface{}) *mock.Call {
	return m.Mock.On(methodName, arguments...)
}

// AssertExpectations provides a mock function with given fields: t
func (m *UserService) AssertExpectations(t mock.TestingT) bool {
	return m.Mock.AssertExpectations(t)
}
